name: Deploy

on:
  push:
    branches:
      - master # 触发条件：当master分支有代码被push时触发构建

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # 将代码检出到Workflow环境

      - name: Install and build
        run: |
          npm install
          npm run build # 构建Vue项目

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3 # GitHub Action打包后推送到gh-pages分支
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }} # 环境变量ACCESS_TOKEN用于访问GitHub API，需事先设置
          publish_dir: ./dist # 打包后的文件所在目录，这里假设是dist\
          cname: ./public/CNAME # 指定CNAME文件所在路径
